apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wildflyservers.wildfly.org
spec:
  group: wildfly.org
  names:
    kind: WildFlyServer
    listKind: WildFlyServerList
    plural: wildflyservers
    singular: wildflyserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            applicationImage:
              type: string
            securityContext:
              type: object
            size:
              format: int32
              type: integer
            storage:
              properties:
                emptyDir:
                  type: object
                volumeClaimTemplate:
                  type: object
              type: object
          required:
          - applicationImage
          - size
          type: object
        status:
          properties:
            nodes:
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
