apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: wildfly-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - wildfly.org
  resources:
  - '*'
  verbs:
  - '*'

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: wildfly-operator


---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wildfly-operator
subjects:
- kind: ServiceAccount
  name: wildfly-operator
roleRef:
  kind: Role
  name: wildfly-operator
  apiGroup: rbac.authorization.k8s.io
