apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: wildfly-operator
  namespace: myproject
users:
- system:serviceaccount:myproject:wildfly-operator
requiredDropCapabilities:
- MKNOD
- SYS_CHROOT
runAsUser:
  type: MustRunAs
  uid: 1000
fsGroup:
  type: MustRunAs
  ranges:
    - min: 2000
      max: 2000
seLinuxContext:
  type: MustRunAs
volumes:
- configMap
- emptyDir
- persistentVolumeClaim
- secret