apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: taskrs-app
spec:
  applicationImage: "quay.io/jfdenise/taskrs-app@sha256:8eb374514d4bd504e699046fbea74082cb1e0575852e5a1a7fa03c1e78e20275"
  size: 2
  env:
  - name: POSTGRESQL_SERVICE_HOST
    value: postgresql
  - name: POSTGRESQL_SERVICE_PORT
    value: '5432'
  - name: POSTGRESQL_DATABASE
    valueFrom:
      secretKeyRef:
        key: database-name
        name: postgresql
  - name: POSTGRESQL_USER
    valueFrom:
      secretKeyRef:
        key: database-user
        name: postgresql
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-password
        name: postgresql
