name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Build
      run: make build
    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.3.0
      with:
        minikube version: v1.16.0
        kubernetes version: v1.20.0
        driver: docker
    - name: Containerized End-to-End Tests
      run: eval $(minikube -p minikube docker-env) && make test-e2e-minikube
